#!/bin/bash

# White-Label Setup Script for Typebot
# This script helps configure environment variables for white-labeling
#
# Usage:
#   chmod +x scripts/setup-white-label.sh
#   ./scripts/setup-white-label.sh

set -e

echo "================================================"
echo "🎨 Typebot White-Label Configuration Setup"
echo "================================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if .env exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠️  .env file already exists!${NC}"
    read -p "Do you want to backup and create a new one? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        BACKUP_FILE=".env.backup.$(date +%Y%m%d_%H%M%S)"
        cp .env "$BACKUP_FILE"
        echo -e "${GREEN}✓ Backed up to $BACKUP_FILE${NC}"
    else
        echo "Exiting without changes."
        exit 0
    fi
fi

# Copy from example
if [ -f .env.example ]; then
    cp .env.example .env
    echo -e "${GREEN}✓ Created .env from .env.example${NC}"
else
    echo -e "${YELLOW}⚠️  .env.example not found, creating new .env${NC}"
    touch .env
fi

echo ""
echo -e "${BLUE}Please provide your brand information:${NC}"
echo ""

# Collect brand information
read -p "Brand Name (short, e.g., 'MyBot'): " BRAND_NAME
BRAND_NAME=${BRAND_NAME:-MyBot}

read -p "Brand Display Name (full, e.g., 'My Awesome Bot'): " BRAND_DISPLAY_NAME
BRAND_DISPLAY_NAME=${BRAND_DISPLAY_NAME:-$BRAND_NAME}

read -p "Brand Tagline: " BRAND_TAGLINE
BRAND_TAGLINE=${BRAND_TAGLINE:-Build powerful chatbots visually}

read -p "Company Name: " COMPANY_NAME
COMPANY_NAME=${COMPANY_NAME:-$BRAND_NAME}

read -p "Support Email: " SUPPORT_EMAIL
SUPPORT_EMAIL=${SUPPORT_EMAIL:-support@example.com}

read -p "Primary Color (hex, e.g., #0066CC): " BRAND_PRIMARY_COLOR
BRAND_PRIMARY_COLOR=${BRAND_PRIMARY_COLOR:-#FF5925}

read -p "Builder Domain (e.g., app.yourbrand.com): " BUILDER_DOMAIN
BUILDER_DOMAIN=${BUILDER_DOMAIN:-localhost:3000}

read -p "Viewer Domain (e.g., chat.yourbrand.com): " VIEWER_DOMAIN
VIEWER_DOMAIN=${VIEWER_DOMAIN:-localhost:3001}

# Generate encryption secret if needed
if ! grep -q "^ENCRYPTION_SECRET=" .env 2>/dev/null || [ -z "$(grep "^ENCRYPTION_SECRET=" .env | cut -d'=' -f2)" ]; then
    echo ""
    echo -e "${BLUE}Generating encryption secret...${NC}"
    ENCRYPTION_SECRET=$(openssl rand -base64 32 | tr -d '\n')
else
    ENCRYPTION_SECRET=$(grep "^ENCRYPTION_SECRET=" .env | cut -d'=' -f2)
fi

# Ask about billing
echo ""
echo -e "${BLUE}Billing Configuration:${NC}"
read -p "Disable billing/subscriptions? (Y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]; then
    DISABLE_BILLING=false
    BILLING_MODE=STRIPE
else
    DISABLE_BILLING=true
    BILLING_MODE=UNLIMITED
fi

# Determine protocol
if [[ $BUILDER_DOMAIN == localhost* ]]; then
    PROTOCOL="http"
else
    PROTOCOL="https"
fi

# Write to .env
echo ""
echo -e "${BLUE}Writing configuration to .env...${NC}"

cat >> .env << EOF

# ================================
# Generated by setup-white-label.sh on $(date)
# ================================

# Core Configuration
ENCRYPTION_SECRET=$ENCRYPTION_SECRET
DATABASE_URL=postgresql://postgres:typebot@localhost:5432/${BRAND_NAME,,}_db
NEXTAUTH_URL=$PROTOCOL://$BUILDER_DOMAIN
NEXT_PUBLIC_VIEWER_URL=$PROTOCOL://$VIEWER_DOMAIN

# Brand Identity
BRAND_NAME=$BRAND_NAME
BRAND_DISPLAY_NAME="$BRAND_DISPLAY_NAME"
BRAND_TAGLINE="$BRAND_TAGLINE"

# Company Information
COMPANY_NAME="$COMPANY_NAME"
COMPANY_LEGAL_NAME="$COMPANY_NAME"
SUPPORT_EMAIL=$SUPPORT_EMAIL
SALES_EMAIL=$SUPPORT_EMAIL

# Visual Branding
BRAND_PRIMARY_COLOR=$BRAND_PRIMARY_COLOR
NEXT_PUBLIC_BRAND_PRIMARY_COLOR=$BRAND_PRIMARY_COLOR

# Client-side Branding (required for UI)
NEXT_PUBLIC_BRAND_NAME=$BRAND_NAME
NEXT_PUBLIC_BRAND_DISPLAY_NAME="$BRAND_DISPLAY_NAME"
NEXT_PUBLIC_BRAND_TAGLINE="$BRAND_TAGLINE"
NEXT_PUBLIC_COMPANY_NAME="$COMPANY_NAME"
NEXT_PUBLIC_SUPPORT_EMAIL=$SUPPORT_EMAIL

# Domains
NEXT_PUBLIC_BUILDER_URL=$PROTOCOL://$BUILDER_DOMAIN
NEXT_PUBLIC_LANDING_URL=$PROTOCOL://${BUILDER_DOMAIN%%:*}
NEXT_PUBLIC_DOCS_URL=$PROTOCOL://docs.${BUILDER_DOMAIN%%:*}

# Feature Flags
SHOW_TYPEBOT_BRANDING=false
SHOW_POWERED_BY=false

# Billing Configuration
DISABLE_BILLING=$DISABLE_BILLING
BILLING_MODE=$BILLING_MODE

# ================================
# End of generated configuration
# ================================
EOF

echo -e "${GREEN}✓ Configuration written successfully!${NC}"
echo ""

# Apply brand colors to CSS files
echo -e "${BLUE}Applying brand colors to CSS files...${NC}"

# Function to convert hex to rgb
hex_to_rgb() {
    local hex=$1
    hex=${hex#"#"}
    printf "rgb(%d %d %d)" 0x${hex:0:2} 0x${hex:2:2} 0x${hex:4:2}
}

# Function to lighten/darken color (simple approximation)
lighten_color() {
    local hex=$1
    local factor=$2
    hex=${hex#"#"}
    local r=$((0x${hex:0:2}))
    local g=$((0x${hex:2:2}))
    local b=$((0x${hex:4:2}))

    r=$(( r + (255 - r) * factor / 100 ))
    g=$(( g + (255 - g) * factor / 100 ))
    b=$(( b + (255 - b) * factor / 100 ))

    printf "#%02x%02x%02x" $r $g $b
}

darken_color() {
    local hex=$1
    local factor=$2
    hex=${hex#"#"}
    local r=$((0x${hex:0:2}))
    local g=$((0x${hex:2:2}))
    local b=$((0x${hex:4:2}))

    r=$(( r * (100 - factor) / 100 ))
    g=$(( g * (100 - factor) / 100 ))
    b=$(( b * (100 - factor) / 100 ))

    printf "#%02x%02x%02x" $r $g $b
}

# Generate color shades
PRIMARY_RGB=$(hex_to_rgb "$BRAND_PRIMARY_COLOR")
PRIMARY_DARK=$(darken_color "$BRAND_PRIMARY_COLOR" 10)
PRIMARY_DARKER=$(darken_color "$BRAND_PRIMARY_COLOR" 20)
PRIMARY_LIGHT=$(lighten_color "$BRAND_PRIMARY_COLOR" 30)
PRIMARY_LIGHTER=$(lighten_color "$BRAND_PRIMARY_COLOR" 50)
PRIMARY_LIGHTEST=$(lighten_color "$BRAND_PRIMARY_COLOR" 70)

# Update packages/ui/src/colors.ts
if [ -f "packages/ui/src/colors.ts" ]; then
    sed -i "s/#04ce56/$BRAND_PRIMARY_COLOR/g" packages/ui/src/colors.ts
    sed -i "s/#03b54a/$PRIMARY_DARK/g" packages/ui/src/colors.ts
    echo -e "${GREEN}  ✓ Updated packages/ui/src/colors.ts${NC}"
fi

# Update packages/ui/src/colors.css
if [ -f "packages/ui/src/colors.css" ]; then
    sed -i "s/rgb(4 206 86)/$PRIMARY_RGB/g" packages/ui/src/colors.css
    sed -i "s/rgb(3 181 74)/$(hex_to_rgb "$PRIMARY_DARK")/g" packages/ui/src/colors.css
    echo -e "${GREEN}  ✓ Updated packages/ui/src/colors.css${NC}"
fi

# Update apps/builder/src/assets/styles/custom.css
if [ -f "apps/builder/src/assets/styles/custom.css" ]; then
    # Replace the hardcoded hex color comment
    sed -i "s|/\* #04ce56 \*/|/* $BRAND_PRIMARY_COLOR */|g" apps/builder/src/assets/styles/custom.css
    sed -i "s|/\* #03b54a \*/|/* $PRIMARY_DARK */|g" apps/builder/src/assets/styles/custom.css
    echo -e "${GREEN}  ✓ Updated apps/builder/src/assets/styles/custom.css${NC}"
fi

# Update apps/docs/mint.json
if [ -f "apps/docs/mint.json" ]; then
    sed -i "s/\"primary\": \"#04ce56\"/\"primary\": \"$BRAND_PRIMARY_COLOR\"/g" apps/docs/mint.json
    sed -i "s/\"light\": \"#04ce56\"/\"light\": \"$BRAND_PRIMARY_COLOR\"/g" apps/docs/mint.json
    sed -i "s/\"dark\": \"#04ce56\"/\"dark\": \"$BRAND_PRIMARY_COLOR\"/g" apps/docs/mint.json
    echo -e "${GREEN}  ✓ Updated apps/docs/mint.json${NC}"
fi

echo -e "${GREEN}✓ Brand colors applied successfully!${NC}"
echo ""

# Summary
echo "================================================"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "================================================"
echo ""
echo "Your configuration:"
echo "  Brand Name: $BRAND_NAME"
echo "  Display Name: $BRAND_DISPLAY_NAME"
echo "  Primary Color: $BRAND_PRIMARY_COLOR"
echo "  Builder URL: $PROTOCOL://$BUILDER_DOMAIN"
echo "  Viewer URL: $PROTOCOL://$VIEWER_DOMAIN"
echo "  Billing: $BILLING_MODE"
echo ""
echo "Next steps:"
echo ""
echo -e "${BLUE}1. Install dependencies:${NC}"
echo "   bun install"
echo ""
echo -e "${BLUE}2. Replace logo assets:${NC}"
echo "   - apps/builder/public/favicon.svg"
echo "   - apps/builder/public/images/logo.png"
echo "   - apps/landing-page/public/images/favicon.svg"
echo ""
echo -e "${BLUE}3. Set up your database:${NC}"
echo "   createdb ${BRAND_NAME,,}_db"
echo "   or update DATABASE_URL in .env"
echo ""
echo -e "${BLUE}4. Run the development server:${NC}"
echo "   bun run dev"
echo ""
echo -e "${BLUE}5. For production:${NC}"
echo "   bun run build"
echo "   bun start"
echo ""
echo "For more information, see:"
echo "  - /docs/DEPLOYMENT_GUIDE.md"
echo "  - /docs/IMPLEMENTATION_LOG.md"
echo "  - /docs/CODEBASE_ANALYSIS.md"
echo ""
echo "================================================"
